### ISSUE TITLE
지전거, 걷기/뛰기 통합 및 구별 기능 및 속도 감지 기능  

### ISSUE THREAD

**Issue by MyungwoonKim** [MyungwoonKim/goToSchool#12]
@MyungwoonKim 
지전거 기능, 걷기/뛰기 기능 분활
속도 감지를 통해 처리

**Comment by gj1534** [comment]
지전거가 뭐죠???

**Comment by MyungwoonKim** [comment]
@gj1534 
>자전거가 뭐죠???

자전거를 이용해 정문을 올라갈 시에 사용되는 기능을 말합니다. 차후 기능은 변경 될 수 있습니다.
